### PR TITLE
[IMP] spreadsheet_oca : Improve documentation

### LINKED ISSUE #25: RFC - Documentation
Hi all, (and specially @etobella).
first thanks for this interesting modules.
I'll soon migrate to V16 and I'd like to use OCA / spreadsheet modules that looks promizing. 
But the documentation is very limited. I'd like to propose a PR to add description & screenshot in the readme.

Is the modules working like the odoo EE one ? (https://www.odoo.com/documentation/16.0/applications/finance/spreadsheet.html?highlight=spreadsheet)

thanks.

### PR DESCRIPTION
**Pull request by legalsylvain**
### Summary of changes

- Adding Usage part in the main ``spreadsheet_oca`` module.
- Add demo data.
- Closes #25 

### Preview

**Create a new spreadsheet**

* Go to 'Spreadsheet' menu
* Click on 'Create'
* Put a name, then click on the "Edit" button

spreadsheet_create

* At this point you switch to spreadsheet editing mode.
  The editor is named ``o-spreadsheet`` and looks like another common spreadsheet web editors.
  (OnlyOffice, Ethercalc, Google Sheets (non-free)).

spreadsheet_edit

* You can use common functions ``SUM()``, ``AVERAGE()``, etc. in the cells.
  For a complete list of functions and their syntax,
  Refer to the documentation https://github.com/odoo/o-spreadsheet/
  or go to https://odoo.github.io/o-spreadsheet/ and click on "Insert > Function".

o-spreadsheet

* Note: Business Odoo module can add "business functions".
  This is currently the case for the accounting module, which adds the following features:

    * ``ODOO.CREDIT(account_codes, date_range)``: Get the total credit for the specified account(s) and period.
    * ``ODOO.DEBIT(account_codes, date_range)``: Get the total debit for the specified account(s) and period.
    * ``ODOO.BALANCE(account_codes, date_range)``: Get the total balance for the specified account(s) and period.
    * ``ODOO.FISCALYEAR.START(day)``: Returns the starting date of the fiscal year encompassing the provided date.
    * ``ODOO.FISCALYEAR.END(day)``: Returns the ending date of the fiscal year encompassing the provided date.
    * ``ODOO.ACCOUNT.GROUP(type)``: Returns the account ids of a given group where type should be a value of the ``account_type`` field of ``account.account`` model.
    (``income``, ``asset_receivable``, etc.)

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Comment by legalsylvain** [comment]
Thanks for your review ! 

Merging, as documentation is harmless.

/ocabot merge patch

Note : I have a question I wrote here https://github.com/OCA/spreadsheet/issues/25#issuecomment-1986132055 any insight are welcome !
thanks !

**Comment by legalsylvain** [comment]
@OCA-git-bot, that's not very nice of you.

**Comment by legalsylvain** [comment]
Second try ! 
/ocabot merge patch

**Comment by legalsylvain** [comment]
Third try !
/ocabot merge patch

**Comment by hitrosol** [comment]
@legalsylvain I try on Runboat, but can't find the icon in the sub-menu spreadsheet. 
Screen Shot 2024-03-18 at 08 04 14


Any guidance about this ?

**Comment by legalsylvain** [comment]
_or go to https://odoo.github.io/o-spreadsheet/ and click on "Insert > Function"_

**Pull request merged**
