### PR TITLE
[16.0][IMP] spreadsheet_*_oca: Add possibility to make columns dynamic

### PR DESCRIPTION
**Pull request by CarlosRoca13**
With these changes, we have added the ability to make the columns dynamic, just as is done with the rows.

To add this type of table, we will need to select the dynamic columns option and choose the number of columns to insert. Keep in mind that if multiple column levels are selected, the chosen number will apply to each of these levels.

In addition to this, the wizard that opens with the spreadsheet button has been updated to allow us to choose the type of dynamism we expect in the inserted table.

Example of use:
example

TT50606

ping @pedrobaeza @chienandalu

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Just a little detail:

image

**Comment by CarlosRoca13** [comment]
Change done

**Review by chienandalu — APPROVED** [review]
Code and functional :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
