### PR TITLE
[16.0][FIX] spreadsheet_oca: Show the "Add" button in invoice list

### PR DESCRIPTION
**Pull request by CarlosRoca13**
If this files aren't charged just after the main file if some module that is charged before spreadsheet_oca makes a primary template, the button will not be shown.

Exmple:
image

cc @Tecnativa TT50815

ping @pedrobaeza @chienandalu

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Tested an working. The only comment is about the commit message. It's a FIX instead of an IMP, as there's something not working, and the first line should express what is fixing:

```
[FIX] spreadsheet_oca: Show the "Add" button in invoice list

If any module males a primary template from the ones where the button is added, the button wasn't be shown previously.

That's because the inheritance and load order works in OWL. The way to fix this is to make this load order deterministic specifying to be loaded after the corresponding template for being taken into account for primary views. This also required to split the templates file into several ones.
```

**Comment by CarlosRoca13** [comment]
Change done @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Pull request merged**
