### PR TITLE
[IMP] spreadsheet_oca: Allow to import to existent spreadsheets

### PR DESCRIPTION
**Pull request by etobella**
Affects to both modules

@pedrobaeza

### CODE REVIEW

**Comment by etobella** [comment]
Peek 2023-01-20 22-58

**Comment by pedrobaeza** [comment]
Thanks for this feature, Enric!

Testing on runboat, I found that adding to an existing spreadsheet, it replaces the content that existed on the first cell, so resulting that you can't add 2 pivots through this technique without any in-between manipulation.

Is it possible to insert the pivot table in the first empty row?

**Comment by etobella** [comment]
Well, it is added on a new sheet, so I don't see the problem :thinking: 

We can try to add to the last line, but I think it might be better to use a new sheet in order to avoid errors

**Comment by jiivii252** [comment]
Help me informasi 🤔

**Comment by pedrobaeza** [comment]
@etobella thanks for the extra features, that are also very important.

The question I comment is still important, as this replaces anything you have, being a previous pivot, graph, text, or whatever, so you adding to an existing spreadsheet should add such content on the first empty row.

**Comment by pedrobaeza** [comment]
Ey, what I'm seeing now is that it's put in a new sheet instead. That's a bit confusing...

**Comment by etobella** [comment]
Well, we can try to add it to the end, but it will be at the end of the first sheet, as we are unable to know which is the right one... It mitght be possible (not sure) to find the sheets and allow to add it where we want by the user, but it is confusing IMO.

At the end, I think Odoo is doing a similar approach :thinking:

**Comment by pedrobaeza** [comment]
Isn't there "active sheet"? If so, we can add it at the end of such active one.

**Comment by etobella** [comment]
But, If two users accessed the view, they might have different active sheets. In this case, we should need to create a list of users/sheets in order to fix that. However, if another user removes the last sheet you opened, that might be a problem :sob:

**Comment by pedrobaeza** [comment]
OK, I think a good compromise is to add it always at the end of the first sheet. The question is not to force people to move the content from the newly created sheet to the one they want (which will be 99% of the times the first one).

**Comment by etobella** [comment]
After reviewing the options, I am able to add it at the end of the sheet, but I found an issue. On sheet creation, the system adds 100 rows, so it will be added at row 100 on small sheets, this can be confusing :sob: I may try to move the view there, but then, we will need to remove rows. WDYT?

The other option, would be to check line by line from the last one, but that can be an extra cost :sad:

**Comment by pedrobaeza** [comment]
As the operation is only done on specific moments, I don't think checking the content of the cells reverse from down to top until the first with content is found is too much. Have you tried to see the times?

**Comment by etobella** [comment]
@pedrobaeza I was able to do something for pivot tables. It does not work properly for graphs

**Review by pedrobaeza — APPROVED** [review]
OK, I think it's enough for now, as the graph doesn't erase previous data. It simply gets over the rest and you can drag and drop it.

Thanks for the efforts!

/ocabot merge minor

**Pull request merged**
